  # This section is used for connect to server
  # name - this field is used for naming task
  # hosts - in this field we are define hostname/server, in which we want to connect
  # remote_user - this field define user, which we want to use for connect into server
  # become - because we dont want to use root user, we must use sudo privilleges and for this we must set value "yes"
  
- name : Connecting to server  
  hosts: 10.0.0.72
  remote_user: azureuser
  become: yes


  # This section is used for define all tasks, which we want to do.
  # roles - there we have defined "sections", which will be used.

  roles: 
    - server
    - php
    - mysql
    - wordpress
    
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
        
    - name: Update apt and install rsyslog
      apt:
        pkg:
          - rsyslog
        state: latest
        update_cache: true

    - name: Configure rsyslog to send logs to syslog server
      become: yes
      lineinfile:
        dest: /etc/rsyslog.conf
        regexp: '\Z'
        line: "*.* @@{{ nagios_log_server }}:{{ nagios_log_port }}"

    - name: Restart rsyslog service
      service: name=rsyslog state=restarted
